# This file should be created on a Windows filesystem, and symlinked with
# ln -s /mnt/c/Users/<username>/.config/starship.toml ~/.config/starship.toml on wsl
# add_newline = false

# [line_break]
# disabled = true

# [package]
# disabled = true

[nodejs]
disabled = true

[gcloud]
disabled = true